################################################################################
# WAS Tier - Python Flask API Server
# Aurora MySQL 연동 REST API 서버
################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-code
  namespace: app-fullstack
data:
  app.py: |
    from flask import Flask, jsonify, request
    import mysql.connector
    import os
    import socket
    from datetime import datetime

    app = Flask(__name__)

    def get_db_connection(use_reader=False):
        """Aurora MySQL 연결 (Writer/Reader 분리)"""
        host = os.environ.get('MYSQL_READ_HOST' if use_reader else 'MYSQL_HOST')
        return mysql.connector.connect(
            host=host,
            port=int(os.environ.get('MYSQL_PORT', 3306)),
            user=os.environ.get('MYSQL_USER'),
            password=os.environ.get('MYSQL_PASSWORD'),
            database=os.environ.get('MYSQL_DATABASE')
        )

    @app.route('/health')
    def health():
        """Health check endpoint"""
        return jsonify({
            'status': 'healthy',
            'hostname': socket.gethostname(),
            'timestamp': datetime.now().isoformat()
        })

    @app.route('/api/db-check')
    def db_check():
        """Database 연결 테스트"""
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            cursor.execute("SELECT 1")
            cursor.fetchone()
            cursor.close()
            conn.close()
            return jsonify({
                'status': 'connected',
                'database': os.environ.get('MYSQL_DATABASE'),
                'host': os.environ.get('MYSQL_HOST')
            })
        except Exception as e:
            return jsonify({'status': 'error', 'message': str(e)}), 500

    @app.route('/api/users')
    def get_users():
        """사용자 목록 조회 (Reader 사용)"""
        try:
            conn = get_db_connection(use_reader=True)
            cursor = conn.cursor(dictionary=True)
            cursor.execute("SELECT * FROM users")
            users = cursor.fetchall()
            cursor.close()
            conn.close()
            return jsonify({'users': users, 'count': len(users)})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    @app.route('/api/products')
    def get_products():
        """상품 목록 조회 (Reader 사용)"""
        try:
            conn = get_db_connection(use_reader=True)
            cursor = conn.cursor(dictionary=True)
            cursor.execute("SELECT * FROM products")
            products = cursor.fetchall()
            cursor.close()
            conn.close()
            # Decimal을 float으로 변환
            for p in products:
                if p.get('price'):
                    p['price'] = float(p['price'])
            return jsonify({'products': products, 'count': len(products)})
        except Exception as e:
            return jsonify({'error': str(e)}), 500

    @app.route('/api/orders', methods=['GET', 'POST'])
    def orders():
        """주문 조회/생성 (Writer 사용)"""
        try:
            conn = get_db_connection(use_reader=(request.method == 'GET'))
            cursor = conn.cursor(dictionary=True)

            if request.method == 'POST':
                data = request.json
                cursor.execute("""
                    INSERT INTO orders (user_id, product_id, quantity, total_price)
                    VALUES (%s, %s, %s, %s)
                """, (data['user_id'], data['product_id'], data['quantity'], data['total_price']))
                conn.commit()
                return jsonify({'message': 'Order created', 'id': cursor.lastrowid}), 201
            else:
                cursor.execute("""
                    SELECT o.*, u.username, p.name as product_name
                    FROM orders o
                    JOIN users u ON o.user_id = u.id
                    JOIN products p ON o.product_id = p.id
                """)
                orders = cursor.fetchall()
                for o in orders:
                    if o.get('total_price'):
                        o['total_price'] = float(o['total_price'])
                return jsonify({'orders': orders, 'count': len(orders)})
        except Exception as e:
            return jsonify({'error': str(e)}), 500
        finally:
            cursor.close()
            conn.close()

    @app.route('/api/info')
    def info():
        """시스템 정보"""
        return jsonify({
            'tier': 'WAS (Application)',
            'technology': 'Python Flask',
            'hostname': socket.gethostname(),
            'database': {
                'writer': os.environ.get('MYSQL_HOST'),
                'reader': os.environ.get('MYSQL_READ_HOST'),
                'name': os.environ.get('MYSQL_DATABASE')
            },
            'timestamp': datetime.now().isoformat()
        })

    if __name__ == '__main__':
        app.run(host='0.0.0.0', port=8080)

  requirements.txt: |
    flask==3.0.0
    mysql-connector-python==8.2.0
    gunicorn==21.2.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: app-fullstack
  labels:
    app: api-server
    tier: was
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
        tier: was
    spec:
      initContainers:
        - name: setup
          image: python:3.11-slim
          command:
            - sh
            - -c
            - |
              pip install -r /app/requirements.txt -t /app-deps
          volumeMounts:
            - name: code
              mountPath: /app
            - name: deps
              mountPath: /app-deps
      containers:
        - name: api
          image: python:3.11-slim
          command:
            - sh
            - -c
            - |
              export PYTHONPATH=/app-deps:$PYTHONPATH
              cd /app && python -m gunicorn -w 2 -b 0.0.0.0:8080 app:app
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_HOST
            - name: MYSQL_READ_HOST
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_READ_HOST
            - name: MYSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_PORT
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: aurora-credentials
                  key: MYSQL_DATABASE
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: code
              mountPath: /app
            - name: deps
              mountPath: /app-deps
      volumes:
        - name: code
          configMap:
            name: api-server-code
        - name: deps
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: app-fullstack
spec:
  type: ClusterIP
  selector:
    app: api-server
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
