################################################################################
# Tomcat WAS Deployment
# 백엔드 애플리케이션 서버 역할
################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-was
  namespace: demo-app
  labels:
    app: tomcat-was
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat-was
  template:
    metadata:
      labels:
        app: tomcat-was
        tier: backend
    spec:
      containers:
        - name: tomcat
          image: tomcat:10-jdk17-temurin-jammy
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
---
################################################################################
# Tomcat Service - ClusterIP (내부 통신용)
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: tomcat-was-service
  namespace: demo-app
spec:
  type: ClusterIP
  selector:
    app: tomcat-was
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
################################################################################
# Tomcat Service - LoadBalancer (외부 접근용, 테스트 목적)
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: tomcat-was-external
  namespace: demo-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: tomcat-was
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
