################################################################################
# Nginx Web Server Deployment
# 프론트엔드 웹서버 역할
################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: app-demo
  labels:
    app: nginx-web
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
        tier: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-index-html
---
################################################################################
# Nginx ConfigMap - 커스텀 index.html
################################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
  namespace: app-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>JSJ EKS Demo</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                display: flex;
                justify-content: center;
                align-items: center;
                height: 100vh;
                margin: 0;
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                color: white;
            }
            .container {
                text-align: center;
                padding: 40px;
                background: rgba(255,255,255,0.1);
                border-radius: 20px;
                backdrop-filter: blur(10px);
            }
            h1 { font-size: 2.5em; margin-bottom: 10px; }
            p { font-size: 1.2em; opacity: 0.9; }
            .info { margin-top: 20px; font-size: 0.9em; opacity: 0.7; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>JSJ EKS Cluster</h1>
            <p>Nginx Web Server is Running!</p>
            <div class="info">
                <p>Environment: Production</p>
                <p>Region: ap-northeast-2</p>
            </div>
        </div>
    </body>
    </html>
---
################################################################################
# Nginx Service - ClusterIP (Ingress 사용)
################################################################################
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: app-demo
spec:
  type: ClusterIP
  selector:
    app: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
################################################################################
# Nginx Ingress - ALB
################################################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-web-ingress
  namespace: app-demo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-web-service
                port:
                  number: 80
