################################################################################
# ArgoCD Application - PetClinic
# 3-tier 아키텍처 테스트 애플리케이션 (Nginx + Spring Boot + Aurora MySQL)
################################################################################
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: petclinic
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    environment: prod
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/JSJ2337/AWS_EKS_terraform_code.git
    targetRevision: main
    path: k8s-manifests/petclinic

  destination:
    server: https://kubernetes.default.svc
    namespace: petclinic

  # 프로덕션: 수동 Sync (auto sync 비활성화)
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
