################################################################################
# Web Tier - Nginx Reverse Proxy + Frontend
# 프론트엔드 UI + API Proxy
################################################################################
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fullstack-demo
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        upstream api_backend {
            server api-server-service:8080;
        }

        server {
            listen 80;
            server_name _;

            # Health check
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # API Proxy to WAS
            location /api/ {
                proxy_pass http://api_backend;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }

            # Frontend
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
            }
        }
    }

  index.html: |
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>3-Tier Fullstack Demo</title>
        <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
                font-family: 'Segoe UI', Arial, sans-serif;
                background: linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%);
                color: white;
                min-height: 100vh;
                padding: 20px;
            }
            .container { max-width: 1200px; margin: 0 auto; }
            h1 { text-align: center; margin-bottom: 30px; font-size: 2.5em; }
            .subtitle { text-align: center; color: #64b5f6; margin-bottom: 40px; }

            .architecture {
                display: flex;
                justify-content: center;
                gap: 20px;
                margin-bottom: 40px;
                flex-wrap: wrap;
            }
            .tier-box {
                background: rgba(255,255,255,0.1);
                padding: 20px;
                border-radius: 15px;
                text-align: center;
                min-width: 200px;
                backdrop-filter: blur(10px);
            }
            .tier-box h3 { color: #ffd700; margin-bottom: 10px; }
            .tier-box .tech { color: #64b5f6; font-size: 0.9em; }
            .arrow { font-size: 2em; color: #ffd700; align-self: center; }

            .status-panel {
                background: rgba(255,255,255,0.1);
                padding: 25px;
                border-radius: 15px;
                margin-bottom: 30px;
            }
            .status-panel h2 { margin-bottom: 20px; color: #64b5f6; }
            .status-grid {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 15px;
            }
            .status-card {
                background: rgba(0,0,0,0.3);
                padding: 15px;
                border-radius: 10px;
            }
            .status-card h4 { color: #ffd700; margin-bottom: 10px; }
            .status-ok { color: #4caf50; }
            .status-error { color: #f44336; }

            .data-panel {
                background: rgba(255,255,255,0.1);
                padding: 25px;
                border-radius: 15px;
                margin-bottom: 20px;
            }
            .data-panel h2 { margin-bottom: 20px; color: #64b5f6; }
            table {
                width: 100%;
                border-collapse: collapse;
            }
            th, td {
                padding: 12px;
                text-align: left;
                border-bottom: 1px solid rgba(255,255,255,0.2);
            }
            th { color: #ffd700; }
            button {
                background: #2196f3;
                color: white;
                border: none;
                padding: 10px 20px;
                border-radius: 5px;
                cursor: pointer;
                margin: 5px;
            }
            button:hover { background: #1976d2; }
            .loading { color: #ffeb3b; }
            pre {
                background: rgba(0,0,0,0.5);
                padding: 15px;
                border-radius: 10px;
                overflow-x: auto;
                font-size: 0.85em;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>3-Tier Fullstack Demo</h1>
            <p class="subtitle">AWS EKS + Aurora MySQL + ArgoCD GitOps</p>

            <!-- Architecture Diagram -->
            <div class="architecture">
                <div class="tier-box">
                    <h3>Web Tier</h3>
                    <p>Nginx</p>
                    <p class="tech">Reverse Proxy</p>
                    <p class="tech">ALB Ingress</p>
                </div>
                <span class="arrow">&rarr;</span>
                <div class="tier-box">
                    <h3>WAS Tier</h3>
                    <p>Python Flask</p>
                    <p class="tech">REST API</p>
                    <p class="tech">Gunicorn</p>
                </div>
                <span class="arrow">&rarr;</span>
                <div class="tier-box">
                    <h3>DB Tier</h3>
                    <p>Aurora MySQL</p>
                    <p class="tech">Writer + Reader</p>
                    <p class="tech">Multi-AZ</p>
                </div>
            </div>

            <!-- Status Panel -->
            <div class="status-panel">
                <h2>System Status</h2>
                <div class="status-grid">
                    <div class="status-card">
                        <h4>Web Tier (Nginx)</h4>
                        <p id="web-status" class="loading">Checking...</p>
                    </div>
                    <div class="status-card">
                        <h4>WAS Tier (Flask API)</h4>
                        <p id="was-status" class="loading">Checking...</p>
                    </div>
                    <div class="status-card">
                        <h4>DB Tier (Aurora MySQL)</h4>
                        <p id="db-status" class="loading">Checking...</p>
                    </div>
                    <div class="status-card">
                        <h4>System Info</h4>
                        <p id="sys-info" class="loading">Loading...</p>
                    </div>
                </div>
            </div>

            <!-- Data Panels -->
            <div class="data-panel">
                <h2>Products (Reader Endpoint)</h2>
                <button onclick="loadProducts()">Refresh Products</button>
                <table id="products-table">
                    <thead>
                        <tr><th>ID</th><th>Name</th><th>Description</th><th>Price</th><th>Stock</th></tr>
                    </thead>
                    <tbody id="products-body">
                        <tr><td colspan="5" class="loading">Loading...</td></tr>
                    </tbody>
                </table>
            </div>

            <div class="data-panel">
                <h2>Users (Reader Endpoint)</h2>
                <button onclick="loadUsers()">Refresh Users</button>
                <table id="users-table">
                    <thead>
                        <tr><th>ID</th><th>Username</th><th>Email</th><th>Created At</th></tr>
                    </thead>
                    <tbody id="users-body">
                        <tr><td colspan="4" class="loading">Loading...</td></tr>
                    </tbody>
                </table>
            </div>

            <div class="data-panel">
                <h2>API Response (Raw)</h2>
                <button onclick="testDbConnection()">Test DB Connection</button>
                <button onclick="getSystemInfo()">Get System Info</button>
                <pre id="api-response">Click a button to test API...</pre>
            </div>
        </div>

        <script>
            async function checkStatus() {
                // Web tier (nginx) - always ok if page loads
                document.getElementById('web-status').innerHTML = '<span class="status-ok">Running</span>';

                // WAS tier
                try {
                    const res = await fetch('/api/info');
                    const data = await res.json();
                    document.getElementById('was-status').innerHTML =
                        `<span class="status-ok">Running</span><br><small>${data.hostname}</small>`;
                    document.getElementById('sys-info').innerHTML =
                        `<small>Writer: ${data.database.writer}<br>Reader: ${data.database.reader}</small>`;
                } catch (e) {
                    document.getElementById('was-status').innerHTML = '<span class="status-error">Error</span>';
                }

                // DB tier
                try {
                    const res = await fetch('/api/db-check');
                    const data = await res.json();
                    document.getElementById('db-status').innerHTML =
                        data.status === 'connected'
                            ? `<span class="status-ok">Connected</span><br><small>${data.database}</small>`
                            : `<span class="status-error">${data.message}</span>`;
                } catch (e) {
                    document.getElementById('db-status').innerHTML = '<span class="status-error">Connection Failed</span>';
                }
            }

            async function loadProducts() {
                try {
                    const res = await fetch('/api/products');
                    const data = await res.json();
                    const tbody = document.getElementById('products-body');
                    tbody.innerHTML = data.products.map(p =>
                        `<tr><td>${p.id}</td><td>${p.name}</td><td>${p.description}</td><td>${p.price.toLocaleString()}원</td><td>${p.stock}</td></tr>`
                    ).join('');
                } catch (e) {
                    document.getElementById('products-body').innerHTML = `<tr><td colspan="5" class="status-error">Error: ${e.message}</td></tr>`;
                }
            }

            async function loadUsers() {
                try {
                    const res = await fetch('/api/users');
                    const data = await res.json();
                    const tbody = document.getElementById('users-body');
                    tbody.innerHTML = data.users.map(u =>
                        `<tr><td>${u.id}</td><td>${u.username}</td><td>${u.email}</td><td>${u.created_at}</td></tr>`
                    ).join('');
                } catch (e) {
                    document.getElementById('users-body').innerHTML = `<tr><td colspan="4" class="status-error">Error: ${e.message}</td></tr>`;
                }
            }

            async function testDbConnection() {
                try {
                    const res = await fetch('/api/db-check');
                    const data = await res.json();
                    document.getElementById('api-response').textContent = JSON.stringify(data, null, 2);
                } catch (e) {
                    document.getElementById('api-response').textContent = `Error: ${e.message}`;
                }
            }

            async function getSystemInfo() {
                try {
                    const res = await fetch('/api/info');
                    const data = await res.json();
                    document.getElementById('api-response').textContent = JSON.stringify(data, null, 2);
                } catch (e) {
                    document.getElementById('api-response').textContent = `Error: ${e.message}`;
                }
            }

            // Initial load
            checkStatus();
            loadProducts();
            loadUsers();
        </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
  namespace: fullstack-demo
  labels:
    app: nginx-web
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-web
  template:
    metadata:
      labels:
        app: nginx-web
        tier: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: fullstack-demo
spec:
  type: ClusterIP
  selector:
    app: nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fullstack-ingress
  namespace: fullstack-demo
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-web-service
                port:
                  number: 80
