################################################################################
# PetClinic Namespace
################################################################################
apiVersion: v1
kind: Namespace
metadata:
  name: petclinic
  labels:
    app: petclinic
    tier: application
